Behaviour:
  Head:
    Toggles:
      #Wenn zu lange kein Torpfosten gesehen wurde wird kurz auf die Position an der Tropfosten laut LokalGoalModule
      #sein sollte geschaut um die daten zu aktualisieren
      tryRefreshGoalData: False #unused

      #Uses the Visionnformation to focus the goals, if false it will use the information of the GoalModel
      goalVisionTracking: True

      #continous switching between Ball and Goal searching
      switchBallGoalSearch: False

      # track goal while going on position
      track_goal: True

      # try to find the ball on old position
      look_at_old_position: False

    Camera:
            minPan: -125
            minTilt: -65
            maxPan: 125
            maxTilt: 0

            #this is only right for 4:3 resolution!
            cameraAngle: 66.5

            horizontalFactor: 1
            verticalFactor: 0.5625

    Tracking:
        #max Speed for tracking
        maxPanSpeedTracking: 60
        maxTiltSpeedTracking: 60

        # Maximale abweichung bevor gedreht wird
        xSensivity: 0.1
        # Maximale abweichung bevor gedreht wird
        ySensivity: 0.1

        # Idealer Ballmittelpunkt auf y-achse (-11)
        yCenterDefault: 0

        # Goalie soll das Tracking Center weiter oben im Bild haben
        yCenterGoalie: 0.6

        # Time how long to try to track the Ball after we lost it
        trackBallLost: 0.25

        # counter were
        ballFailCounterMax: 17

    Search:
        #max Speed for searching
        maxPanSpeedSearch: 60
        maxTiltSpeedSearch: 60

        # time between steps of the head movement
        headTurnTime: 1.3

        # how exact the head has to be an the position to be recongized as at this position (in degree)
        headTurnPrecision: 2

        # Time in Secounds to wait befor turn by Walking
        turnWaitTime: 20

        #New feature if wew want to use invere kinematics for searching
        useKinematicTaskForSearching: true

        # Time to confirm an object
        confirmTime: 2

    SearchPattern:
    help: |
      These are the search pattern for the head behaviour.
      Each position is a tupel of pan and tilt in degree

    ball:
          - [0 , -12]
          -  [90 , -10]
          -  [50 ,-35]
          -  [ 0 ,-50]
          - [-50 ,-35]
          - [-90 ,-10]

    goalie:
          - [  0 ,-20]
          - [ 90 , -5]
          -  [50 ,-40]
          -  [ 0 ,-60]
          - [-50 ,-40]
          - [-90 ,-20]


    defender:
          - [  0 ,-20]
          - [ 90 , -5]
          - [ 50 ,-40]
          - [  0 ,-60]
          - [-50 ,-40]
          - [-90 ,-20]


    center:
          - [  0 ,-20]
          - [ 90 , -5]
          - [ 50 ,-40]
          - [  0 ,-60]
          - [-50 ,-40]
          - [-90 ,-20]